# Generated by Django 5.2.1 on 2025-05-10 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
