# Generated by Django 5.2.1 on 2025-05-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
